/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaautogestion.zaratesilvachalimond.vista;

import java.awt.CardLayout;

/**
 *
 * @author flore
 */
public class AutogestionView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AutogestionView.class.getName());

    private sistemaautogestion.zaratesilvachalimond.controlador.AutogestionController controlador;
    private String legajoActual = "12345";
    private String codigoMateriaOriginal = ""; // código de la materia seleccionada (clave para actualizar)

    /**
     * Creates new form VentanaPrincipal
     */
    public AutogestionView(sistemaautogestion.zaratesilvachalimond.controlador.AutogestionController controlador) {
        this.controlador = controlador;
        initComponents();
        
        // Vincular manualmente eventos de botones que no estaban mapeados en NetBeans
        if (btnAsistencia != null && btnAsistencia.getActionListeners().length == 0) {
            btnAsistencia.addActionListener(e -> registrarAsistencia());
        }
        
        if (menuSalir != null) {
            menuSalir.addActionListener(e -> System.exit(0));
        }

        this.setLocationRelativeTo(null);
        tblAsistencia.getTableHeader().setBackground(new java.awt.Color(30, 30, 36));
        tblAsistencia.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        tblMaterias.getTableHeader().setBackground(new java.awt.Color(30, 30, 36));
        tblMaterias.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        tblNotas.getTableHeader().setBackground(new java.awt.Color(30, 30, 36));
        tblNotas.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        
        tblMaterias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAsistencia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblNotas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        CardLayout cl = (CardLayout) pnlCentral.getLayout();
        cl.show(pnlCentral, "inicio");

        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ((CardLayout) pnlCentral.getLayout()).show(pnlCentral, "panelInicio");
                resaltarMenu(lblInicio);
            }
        });
        lblMisMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ((CardLayout) pnlCentral.getLayout()).show(pnlCentral, "panelMisMaterias");
                resaltarMenu(lblMisMaterias);
            }
        });
        lblReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ((CardLayout) pnlCentral.getLayout()).show(pnlCentral, "panelReportes");
                resaltarMenu(lblReportes);
            }
        });
        menuReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ((CardLayout) pnlCentral.getLayout()).show(pnlCentral, "panelReportes");
                resaltarMenu(lblReportes);
            }
        });
        
        actualizarTablas();
        
        // Al seleccionar una materia en la tabla de la pestaña "Materias",
        // se cargan sus datos en el formulario de edición.
        tblMaterias.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                cargarDatosEnFormulario();
            }
        });

        btnActualizar.addActionListener(e -> guardarCambiosMateria());

        // El botón del tercer buscador no quedó conectado en el diseñador, lo enganchamos acá
        btnBuscar3.addActionListener(this::btnBuscar3ActionPerformed);

        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                System.exit(0);
            }
        }
        );

        resaltarMenu(lblInicio);
    }

    private void resaltarMenu(javax.swing.JLabel seleccionado) {
        java.awt.Color normal = new java.awt.Color(148, 161, 178);
        java.awt.Color activo = new java.awt.Color(127, 90, 240);

        lblInicio.setForeground(normal);
        lblMisMaterias.setForeground(normal);
        lblReportes.setForeground(normal);

        seleccionado.setForeground(activo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSidebar = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        sep1 = new javax.swing.JSeparator();
        lblMisMaterias = new javax.swing.JLabel();
        sep2 = new javax.swing.JSeparator();
        lblReportes = new javax.swing.JLabel();
        sep3 = new javax.swing.JSeparator();
        sep4 = new javax.swing.JSeparator();
        lblCerrar = new javax.swing.JLabel();
        pnlCentral = new javax.swing.JPanel();
        pnlInicio = new javax.swing.JPanel();
        cardperfil = new javax.swing.JPanel();
        lblNombreTag = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCarreraTag = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblAnioTag = new javax.swing.JLabel();
        scpMateriasDesaprobadas = new javax.swing.JScrollPane();
        listaMaterias = new javax.swing.JList<>();
        lblTituloDesaprobadas = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMaterias1 = new javax.swing.JTable();
        lblTituloSituacionGeneral = new javax.swing.JLabel();
        pnlMisMaterias = new javax.swing.JPanel();
        tabbedMaterias = new javax.swing.JTabbedPane();
        tabMaterias = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMaterias = new javax.swing.JTable();
        btnInscribir = new javax.swing.JButton();
        btnDarBajaMateria = new javax.swing.JButton();
        lblIngresarPorMateria1 = new javax.swing.JLabel();
        txtBuscar1 = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtEditCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtEditAnio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEditCuatrimestre = new javax.swing.JTextField();
        lblCuatrimestre = new javax.swing.JLabel();
        txtEditMateria = new javax.swing.JTextField();
        lblMateria = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        tabAsistencia = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsistencia = new javax.swing.JTable();
        btnAsistencia = new javax.swing.JButton();
        lblIngresarPorMateria2 = new javax.swing.JLabel();
        txtBuscar2 = new javax.swing.JTextField();
        btnBuscar2 = new javax.swing.JButton();
        tabNotas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNotas = new javax.swing.JTable();
        lblIngresarPorMateria3 = new javax.swing.JLabel();
        btnBuscar3 = new javax.swing.JButton();
        txtBuscar3 = new javax.swing.JTextField();
        btnNota = new javax.swing.JButton();
        pnlReportes = new javax.swing.JPanel();
        pnlSituacionGeneral = new javax.swing.JPanel();
        lblTituloSeccionGeneral = new javax.swing.JLabel();
        lblPromedioTag = new javax.swing.JLabel();
        lblRegularesTag = new javax.swing.JLabel();
        lblLibresTag = new javax.swing.JLabel();
        lblRiesgoTag = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        lblRegulares = new javax.swing.JLabel();
        lblLibres = new javax.swing.JLabel();
        lblRiesgo = new javax.swing.JLabel();
        pnlEstadisticaAprobados = new javax.swing.JPanel();
        lblTituloEstadisticas = new javax.swing.JLabel();
        lblMaxTag = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        lblMinTag = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblPromedioStatsTag = new javax.swing.JLabel();
        lblPromedioStats = new javax.swing.JLabel();
        lblTituloReportes = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de autogestión estudiantil");

        pnlSidebar.setBackground(new java.awt.Color(22, 22, 26));
        pnlSidebar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlSidebar.setForeground(new java.awt.Color(40, 40, 40));
        pnlSidebar.setPreferredSize(new java.awt.Dimension(180, 600));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(114, 117, 126));
        lblTitulo.setText("Autogestión alumnos");
        lblTitulo.setAlignmentX(0.5F);

        lblInicio.setBackground(new java.awt.Color(255, 255, 254));
        lblInicio.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblInicio.setText("Inicio");
        lblInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sep1.setBackground(new java.awt.Color(127, 90, 240));
        sep1.setForeground(new java.awt.Color(40, 40, 40));
        sep1.setToolTipText("");

        lblMisMaterias.setBackground(new java.awt.Color(255, 255, 254));
        lblMisMaterias.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblMisMaterias.setText("Mis materias");
        lblMisMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sep2.setBackground(new java.awt.Color(148, 161, 178));
        sep2.setForeground(new java.awt.Color(40, 40, 40));

        lblReportes.setBackground(new java.awt.Color(255, 255, 254));
        lblReportes.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblReportes.setText("Reportes");
        lblReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sep3.setBackground(new java.awt.Color(148, 161, 178));
        sep3.setForeground(new java.awt.Color(40, 40, 40));

        sep4.setForeground(new java.awt.Color(40, 40, 40));

        lblCerrar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(114, 117, 126));
        lblCerrar.setText("Cerrar sesión");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sep1)
            .addComponent(sep2)
            .addComponent(sep4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebarLayout.createSequentialGroup()
                        .addComponent(lblMisMaterias)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebarLayout.createSequentialGroup()
                        .addComponent(lblReportes)
                        .addGap(61, 61, 61))))
            .addComponent(sep3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSidebarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblInicio))
                    .addGroup(pnlSidebarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTitulo))
                    .addGroup(pnlSidebarLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblCerrar)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addGap(49, 49, 49)
                .addComponent(lblInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMisMaterias)
                .addGap(16, 16, 16)
                .addComponent(sep2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReportes)
                .addGap(18, 18, 18)
                .addComponent(sep3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                .addComponent(sep4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCerrar)
                .addGap(14, 14, 14))
        );

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.LINE_START);

        pnlCentral.setBackground(new java.awt.Color(36, 38, 41));
        pnlCentral.setToolTipText("");
        pnlCentral.setLayout(new java.awt.CardLayout());

        pnlInicio.setBackground(new java.awt.Color(22, 22, 26));
        pnlInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 90, 240), 2, true));

        cardperfil.setBackground(new java.awt.Color(22, 22, 26));
        cardperfil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mi perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(113, 78, 218))); // NOI18N
        cardperfil.setForeground(new java.awt.Color(22, 22, 26));

        lblNombreTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreTag.setForeground(new java.awt.Color(255, 255, 254));
        lblNombreTag.setText("Nombre:");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(148, 161, 178));
        lblNombre.setText("Ana García");

        lblCarreraTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCarreraTag.setForeground(new java.awt.Color(255, 255, 254));
        lblCarreraTag.setText("Carrera:");

        lblCarrera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCarrera.setForeground(new java.awt.Color(148, 161, 178));
        lblCarrera.setText("Analista en Sistemas");

        lblAnio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAnio.setForeground(new java.awt.Color(148, 161, 178));
        lblAnio.setText("2023");

        lblAnioTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAnioTag.setForeground(new java.awt.Color(255, 255, 254));
        lblAnioTag.setText("Anio:");

        javax.swing.GroupLayout cardperfilLayout = new javax.swing.GroupLayout(cardperfil);
        cardperfil.setLayout(cardperfilLayout);
        cardperfilLayout.setHorizontalGroup(
            cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardperfilLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardperfilLayout.createSequentialGroup()
                        .addGroup(cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarreraTag)
                            .addComponent(lblNombreTag))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblCarrera)))
                    .addGroup(cardperfilLayout.createSequentialGroup()
                        .addComponent(lblAnioTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAnio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardperfilLayout.setVerticalGroup(
            cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardperfilLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTag)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarreraTag)
                    .addComponent(lblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnioTag)
                    .addComponent(lblAnio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listaMaterias.setBackground(new java.awt.Color(22, 22, 26));
        listaMaterias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scpMateriasDesaprobadas.setViewportView(listaMaterias);

        lblTituloDesaprobadas.setBackground(new java.awt.Color(255, 255, 254));
        lblTituloDesaprobadas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTituloDesaprobadas.setForeground(new java.awt.Color(114, 117, 126));
        lblTituloDesaprobadas.setText("Materias en riesgo");

        tblMaterias1.setBackground(new java.awt.Color(22, 22, 26));
        tblMaterias1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Materia", "Condicion", "Asistencia", "Promedio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMaterias1.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jScrollPane4.setViewportView(tblMaterias1);
        if (tblMaterias1.getColumnModel().getColumnCount() > 0) {
            tblMaterias1.getColumnModel().getColumn(0).setResizable(false);
            tblMaterias1.getColumnModel().getColumn(1).setResizable(false);
            tblMaterias1.getColumnModel().getColumn(2).setResizable(false);
            tblMaterias1.getColumnModel().getColumn(3).setResizable(false);
        }

        lblTituloSituacionGeneral.setBackground(new java.awt.Color(255, 255, 254));
        lblTituloSituacionGeneral.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTituloSituacionGeneral.setForeground(new java.awt.Color(114, 117, 126));
        lblTituloSituacionGeneral.setText("Situacion general");

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scpMateriasDesaprobadas, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(lblTituloDesaprobadas)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloSituacionGeneral)
                    .addComponent(cardperfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(cardperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTituloSituacionGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloDesaprobadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpMateriasDesaprobadas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pnlCentral.add(pnlInicio, "panelInicio");

        pnlMisMaterias.setBackground(new java.awt.Color(22, 22, 26));
        pnlMisMaterias.setLayout(null);

        tabbedMaterias.setBackground(new java.awt.Color(22, 22, 26));

        tabMaterias.setBackground(new java.awt.Color(22, 22, 26));

        tblMaterias.setBackground(new java.awt.Color(22, 22, 26));
        tblMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Codigo", "Cuatrimestre", "Año"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMaterias.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jScrollPane3.setViewportView(tblMaterias);
        if (tblMaterias.getColumnModel().getColumnCount() > 0) {
            tblMaterias.getColumnModel().getColumn(0).setResizable(false);
            tblMaterias.getColumnModel().getColumn(1).setResizable(false);
            tblMaterias.getColumnModel().getColumn(2).setResizable(false);
            tblMaterias.getColumnModel().getColumn(3).setResizable(false);
        }

        btnInscribir.setBackground(new java.awt.Color(127, 90, 240));
        btnInscribir.setText("+ Inscribirse a una materia");
        btnInscribir.addActionListener(this::btnInscribirActionPerformed);

        btnDarBajaMateria.setBackground(new java.awt.Color(22, 22, 26));
        btnDarBajaMateria.setText("Dar de baja una materia");
        btnDarBajaMateria.setAutoscrolls(true);
        btnDarBajaMateria.addActionListener(this::btnDarBajaMateriaActionPerformed);

        lblIngresarPorMateria1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIngresarPorMateria1.setText("Ingresar por materia o codigo");

        txtBuscar1.setToolTipText("");
        txtBuscar1.addActionListener(this::txtBuscar1ActionPerformed);

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(this::btnBuscar1ActionPerformed);

        jPanel1.setBackground(new java.awt.Color(22, 22, 26));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar materia"));

        lblCodigo.setText("Codigo:");

        jLabel5.setText("Anio:");

        lblCuatrimestre.setText("Cuatrimestre:");

        lblMateria.setText("Materia:");

        btnActualizar.setText("Actualizar");
        btnActualizar.setMaximumSize(new java.awt.Dimension(120, 35));
        btnActualizar.setMinimumSize(new java.awt.Dimension(120, 35));
        btnActualizar.setPreferredSize(new java.awt.Dimension(120, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMateria)
                        .addGap(5, 5, 5)
                        .addComponent(txtEditMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblCodigo)
                        .addGap(5, 5, 5)
                        .addComponent(txtEditCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCuatrimestre)
                        .addGap(5, 5, 5)
                        .addComponent(txtEditCuatrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)
                        .addComponent(txtEditAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMateria)
                        .addComponent(txtEditMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigo)
                        .addComponent(txtEditCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblCuatrimestre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditCuatrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtEditAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout tabMateriasLayout = new javax.swing.GroupLayout(tabMaterias);
        tabMaterias.setLayout(tabMateriasLayout);
        tabMateriasLayout.setHorizontalGroup(
            tabMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMateriasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tabMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabMateriasLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(btnInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnDarBajaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblIngresarPorMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabMateriasLayout.createSequentialGroup()
                        .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );
        tabMateriasLayout.setVerticalGroup(
            tabMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMateriasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblIngresarPorMateria1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDarBajaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        tabbedMaterias.addTab("Materias", tabMaterias);

        tabAsistencia.setBackground(new java.awt.Color(22, 22, 26));

        tblAsistencia.setBackground(new java.awt.Color(22, 22, 26));
        tblAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Codigo", "Asistencia %"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAsistencia.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jScrollPane1.setViewportView(tblAsistencia);
        if (tblAsistencia.getColumnModel().getColumnCount() > 0) {
            tblAsistencia.getColumnModel().getColumn(0).setResizable(false);
            tblAsistencia.getColumnModel().getColumn(1).setResizable(false);
            tblAsistencia.getColumnModel().getColumn(2).setResizable(false);
        }

        btnAsistencia.setText("+ Registrar asistencia");

        lblIngresarPorMateria2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIngresarPorMateria2.setText("Ingresar por materia o codigo");

        txtBuscar2.addActionListener(this::txtBuscar2ActionPerformed);

        btnBuscar2.setText("Buscar");
        btnBuscar2.addActionListener(this::btnBuscar2ActionPerformed);

        javax.swing.GroupLayout tabAsistenciaLayout = new javax.swing.GroupLayout(tabAsistencia);
        tabAsistencia.setLayout(tabAsistenciaLayout);
        tabAsistenciaLayout.setHorizontalGroup(
            tabAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAsistenciaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(tabAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIngresarPorMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabAsistenciaLayout.createSequentialGroup()
                        .addComponent(txtBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAsistenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tabAsistenciaLayout.setVerticalGroup(
            tabAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAsistenciaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblIngresarPorMateria2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedMaterias.addTab("Asistencia", tabAsistencia);

        tabNotas.setBackground(new java.awt.Color(22, 22, 26));

        tblNotas.setBackground(new java.awt.Color(22, 22, 26));
        tblNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Codigo", "Promedio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNotas.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jScrollPane2.setViewportView(tblNotas);
        if (tblNotas.getColumnModel().getColumnCount() > 0) {
            tblNotas.getColumnModel().getColumn(0).setResizable(false);
            tblNotas.getColumnModel().getColumn(1).setResizable(false);
            tblNotas.getColumnModel().getColumn(2).setResizable(false);
        }

        lblIngresarPorMateria3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIngresarPorMateria3.setText("Ingresar por materia o codigo");

        btnBuscar3.setText("Buscar");

        txtBuscar3.addActionListener(this::txtBuscar3ActionPerformed);

        btnNota.setText("+ Registrar nota");
        btnNota.addActionListener(this::btnNotaActionPerformed);

        javax.swing.GroupLayout tabNotasLayout = new javax.swing.GroupLayout(tabNotas);
        tabNotas.setLayout(tabNotasLayout);
        tabNotasLayout.setHorizontalGroup(
            tabNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabNotasLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(tabNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabNotasLayout.createSequentialGroup()
                        .addGroup(tabNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIngresarPorMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabNotasLayout.createSequentialGroup()
                                .addComponent(txtBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tabNotasLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabNotasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNota, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tabNotasLayout.setVerticalGroup(
            tabNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabNotasLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblIngresarPorMateria3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNota, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedMaterias.addTab("Notas", tabNotas);

        pnlMisMaterias.add(tabbedMaterias);
        tabbedMaterias.setBounds(20, 51, 465, 590);

        pnlCentral.add(pnlMisMaterias, "panelMisMaterias");

        pnlReportes.setBackground(new java.awt.Color(22, 22, 26));

        pnlSituacionGeneral.setBackground(new java.awt.Color(22, 22, 26));
        pnlSituacionGeneral.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 90, 240), 1, true));

        lblTituloSeccionGeneral.setBackground(new java.awt.Color(114, 117, 126));
        lblTituloSeccionGeneral.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTituloSeccionGeneral.setForeground(new java.awt.Color(242, 242, 242));
        lblTituloSeccionGeneral.setText("Situacion general");

        lblPromedioTag.setBackground(new java.awt.Color(114, 117, 126));
        lblPromedioTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPromedioTag.setForeground(new java.awt.Color(114, 117, 126));
        lblPromedioTag.setText("Promedio general:");

        lblRegularesTag.setBackground(new java.awt.Color(114, 117, 126));
        lblRegularesTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegularesTag.setForeground(new java.awt.Color(114, 117, 126));
        lblRegularesTag.setText("Materias regulares:");

        lblLibresTag.setBackground(new java.awt.Color(114, 117, 126));
        lblLibresTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLibresTag.setForeground(new java.awt.Color(114, 117, 126));
        lblLibresTag.setText("Materias libres:");

        lblRiesgoTag.setBackground(new java.awt.Color(114, 117, 126));
        lblRiesgoTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRiesgoTag.setForeground(new java.awt.Color(114, 117, 126));
        lblRiesgoTag.setText("Materias en riesgo:");

        lblPromedio.setBackground(new java.awt.Color(114, 117, 126));
        lblPromedio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPromedio.setForeground(new java.awt.Color(114, 117, 126));
        lblPromedio.setText("0.0");

        lblRegulares.setBackground(new java.awt.Color(114, 117, 126));
        lblRegulares.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegulares.setForeground(new java.awt.Color(114, 117, 126));
        lblRegulares.setText("0");

        lblLibres.setBackground(new java.awt.Color(114, 117, 126));
        lblLibres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLibres.setForeground(new java.awt.Color(114, 117, 126));
        lblLibres.setText("0");

        lblRiesgo.setBackground(new java.awt.Color(114, 117, 126));
        lblRiesgo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRiesgo.setForeground(new java.awt.Color(114, 117, 126));
        lblRiesgo.setText("0");

        javax.swing.GroupLayout pnlSituacionGeneralLayout = new javax.swing.GroupLayout(pnlSituacionGeneral);
        pnlSituacionGeneral.setLayout(pnlSituacionGeneralLayout);
        pnlSituacionGeneralLayout.setHorizontalGroup(
            pnlSituacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSituacionGeneralLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlSituacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloSeccionGeneral)
                    .addGroup(pnlSituacionGeneralLayout.createSequentialGroup()
                        .addGroup(pnlSituacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPromedioTag)
                            .addComponent(lblRegularesTag)
                            .addGroup(pnlSituacionGeneralLayout.createSequentialGroup()
                                .addComponent(lblLibresTag)
                                .addGap(5, 5, 5)
                                .addComponent(lblLibres))
                            .addComponent(lblRiesgoTag))
                        .addGap(5, 5, 5)
                        .addGroup(pnlSituacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPromedio)
                            .addComponent(lblRegulares)
                            .addComponent(lblRiesgo))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        pnlSituacionGeneralLayout.setVerticalGroup(
            pnlSituacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSituacionGeneralLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblTituloSeccionGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSituacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSituacionGeneralLayout.createSequentialGroup()
                        .addComponent(lblPromedioTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRegularesTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSituacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLibresTag)
                            .addComponent(lblLibres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRiesgoTag))
                    .addGroup(pnlSituacionGeneralLayout.createSequentialGroup()
                        .addComponent(lblPromedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRegulares)
                        .addGap(32, 32, 32)
                        .addComponent(lblRiesgo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEstadisticaAprobados.setBackground(new java.awt.Color(22, 22, 26));
        pnlEstadisticaAprobados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 90, 240), 1, true));

        lblTituloEstadisticas.setBackground(new java.awt.Color(22, 22, 26));
        lblTituloEstadisticas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTituloEstadisticas.setForeground(new java.awt.Color(242, 242, 242));
        lblTituloEstadisticas.setText("Estadística de aprobados");

        lblMaxTag.setBackground(new java.awt.Color(114, 117, 126));
        lblMaxTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaxTag.setForeground(new java.awt.Color(114, 117, 126));
        lblMaxTag.setText("Nota máxima:");

        lblMax.setBackground(new java.awt.Color(114, 117, 126));
        lblMax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMax.setForeground(new java.awt.Color(114, 117, 126));
        lblMax.setText("0.0");

        lblMinTag.setBackground(new java.awt.Color(114, 117, 126));
        lblMinTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMinTag.setForeground(new java.awt.Color(114, 117, 126));
        lblMinTag.setText("Nota mínima:");

        lblMin.setBackground(new java.awt.Color(114, 117, 126));
        lblMin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMin.setForeground(new java.awt.Color(114, 117, 126));
        lblMin.setText("0");

        lblPromedioStatsTag.setBackground(new java.awt.Color(114, 117, 126));
        lblPromedioStatsTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPromedioStatsTag.setForeground(new java.awt.Color(114, 117, 126));
        lblPromedioStatsTag.setText("Promedio");

        lblPromedioStats.setBackground(new java.awt.Color(114, 117, 126));
        lblPromedioStats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPromedioStats.setForeground(new java.awt.Color(114, 117, 126));
        lblPromedioStats.setText("0");

        javax.swing.GroupLayout pnlEstadisticaAprobadosLayout = new javax.swing.GroupLayout(pnlEstadisticaAprobados);
        pnlEstadisticaAprobados.setLayout(pnlEstadisticaAprobadosLayout);
        pnlEstadisticaAprobadosLayout.setHorizontalGroup(
            pnlEstadisticaAprobadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadisticaAprobadosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlEstadisticaAprobadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloEstadisticas)
                    .addGroup(pnlEstadisticaAprobadosLayout.createSequentialGroup()
                        .addGroup(pnlEstadisticaAprobadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaxTag)
                            .addComponent(lblMinTag)
                            .addGroup(pnlEstadisticaAprobadosLayout.createSequentialGroup()
                                .addComponent(lblPromedioStatsTag)
                                .addGap(5, 5, 5)
                                .addComponent(lblPromedioStats)))
                        .addGap(5, 5, 5)
                        .addGroup(pnlEstadisticaAprobadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMax)
                            .addComponent(lblMin))))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        pnlEstadisticaAprobadosLayout.setVerticalGroup(
            pnlEstadisticaAprobadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadisticaAprobadosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblTituloEstadisticas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEstadisticaAprobadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlEstadisticaAprobadosLayout.createSequentialGroup()
                        .addComponent(lblMaxTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMinTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEstadisticaAprobadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPromedioStatsTag)
                            .addComponent(lblPromedioStats)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlEstadisticaAprobadosLayout.createSequentialGroup()
                        .addComponent(lblMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTituloReportes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTituloReportes.setText("Mis reportes");

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloReportes)
                    .addComponent(pnlEstadisticaAprobados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlSituacionGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblTituloReportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSituacionGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlEstadisticaAprobados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        pnlCentral.add(pnlReportes, "panelReportes");

        getContentPane().add(pnlCentral, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("Archivo");

        menuSalir.setText("Salir");
        menuArchivo.add(menuSalir);

        jMenuBar1.add(menuArchivo);

        menuReportes.setText("Reportes");
        jMenuBar1.add(menuReportes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        if (controlador == null) return;
        String legajo = legajoActual;

        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(4, 2));
        panel.add(new javax.swing.JLabel("Nombre de la Materia:"));
        javax.swing.JTextField txtNombre = new javax.swing.JTextField();
        panel.add(txtNombre);
        panel.add(new javax.swing.JLabel("Código (3-10 chars):"));
        javax.swing.JTextField txtCodigo = new javax.swing.JTextField();
        panel.add(txtCodigo);
        panel.add(new javax.swing.JLabel("Cuatrimestre (1 o 2):"));
        javax.swing.JTextField txtCuatrimestre = new javax.swing.JTextField();
        panel.add(txtCuatrimestre);
        panel.add(new javax.swing.JLabel("Año:"));
        javax.swing.JTextField txtAnio = new javax.swing.JTextField();
        panel.add(txtAnio);

        int result = javax.swing.JOptionPane.showConfirmDialog(null, panel, "Inscribir Materia", javax.swing.JOptionPane.OK_CANCEL_OPTION);
        if (result == javax.swing.JOptionPane.OK_OPTION) {
            try {
                int cuat = Integer.parseInt(txtCuatrimestre.getText());
                int anio = Integer.parseInt(txtAnio.getText());
                String msg = controlador.crearMateriaEInscribir(legajo, txtNombre.getText(), txtCodigo.getText(), cuat, anio);
                javax.swing.JOptionPane.showMessageDialog(this, msg);
                actualizarTablas();
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cuatrimestre o Año inválidos.");
            }
        }
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void btnDarBajaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaMateriaActionPerformed
        if (controlador == null) return;
        int row = tblMaterias.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione una materia de la tabla primero.");
            return;
        }
        if (legajoActual.isEmpty()) return;
        
        String nombreMateria = (String) tblMaterias.getValueAt(row, 0);
        Object[] opciones = {"Aceptar", "Cancelar"};
        int confirm = javax.swing.JOptionPane.showOptionDialog(this,
                "¿Está seguro que desea dar de baja la materia " + nombreMateria + "?",
                "Confirmar Baja",
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null, opciones, opciones[0]);
        if (confirm == 0) { // 0 = "Aceptar"
            // Find code
            java.util.List<sistemaautogestion.zaratesilvachalimond.modelos.InscripcionMateria> inscripciones = controlador.listarInscripciones(legajoActual);
            String codigo = "";
            for (sistemaautogestion.zaratesilvachalimond.modelos.InscripcionMateria ins : inscripciones) {
                if (ins.getMateria().getNombre().equals(nombreMateria)) {
                    codigo = ins.getMateria().getCodigo();
                    break;
                }
            }
            if (!codigo.isEmpty()) {
                String msg = controlador.darDeBajaMateria(legajoActual, codigo);
                javax.swing.JOptionPane.showMessageDialog(this, msg);
                actualizarTablas();
            }
        }
    }//GEN-LAST:event_btnDarBajaMateriaActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        buscarYResaltar(tblMaterias, txtBuscar1.getText());
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void txtBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar1ActionPerformed
        btnBuscar1ActionPerformed(evt);
    }//GEN-LAST:event_txtBuscar1ActionPerformed

    private void txtBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar2ActionPerformed
        btnBuscar2ActionPerformed(evt);
    }//GEN-LAST:event_txtBuscar2ActionPerformed

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        buscarYResaltar(tblAsistencia, txtBuscar2.getText());
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void txtBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar3ActionPerformed
        btnBuscar3ActionPerformed(evt);
    }//GEN-LAST:event_txtBuscar3ActionPerformed

    private void btnBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {
        buscarYResaltar(tblNotas, txtBuscar3.getText());
    }

    private void btnNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaActionPerformed
        if (controlador == null) return;
        int row = tblNotas.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione una materia de la tabla de Notas.");
            return;
        }
        if (legajoActual.isEmpty()) return;

        String nombreMateria = (String) tblNotas.getValueAt(row, 0);
        java.util.List<sistemaautogestion.zaratesilvachalimond.modelos.InscripcionMateria> inscripciones = controlador.listarInscripciones(legajoActual);
        String codigo = "";
        for (sistemaautogestion.zaratesilvachalimond.modelos.InscripcionMateria ins : inscripciones) {
            if (ins.getMateria().getNombre().equals(nombreMateria)) {
                codigo = ins.getMateria().getCodigo();
                break;
            }
        }

        if (!codigo.isEmpty()) {
            String notaStr = javax.swing.JOptionPane.showInputDialog(this, "Ingrese Nota (0-10) para " + nombreMateria + ":");
            if (notaStr != null && !notaStr.isEmpty()) {
                try {
                    double nota = Double.parseDouble(notaStr);
                    String msg = controlador.agregarNotaAInscripcion(legajoActual, codigo, nota);
                    javax.swing.JOptionPane.showMessageDialog(this, msg);
                    actualizarTablas();
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Nota inválida.");
                }
            }
        }
    }//GEN-LAST:event_btnNotaActionPerformed

    private void actualizarTablas() {
        if (controlador == null) return;

        // Perfil del estudiante (datos reales que provee el Modelo)
        sistemaautogestion.zaratesilvachalimond.modelos.Estudiante est = controlador.obtenerEstudiante(legajoActual);
        if (est != null) {
            lblNombre.setText(est.getNombre());
            lblCarrera.setText(est.getCarrera());
            lblAnio.setText(String.valueOf(est.getAnioIngreso()));
        } else {
            lblNombre.setText("Estudiante no encontrado");
            lblCarrera.setText("");
            lblAnio.setText("");
        }

        java.util.List<sistemaautogestion.zaratesilvachalimond.modelos.InscripcionMateria> inscripcionesDb = controlador.listarInscripciones(legajoActual);

        javax.swing.table.DefaultTableModel modelMaterias = (javax.swing.table.DefaultTableModel) tblMaterias.getModel();
        javax.swing.table.DefaultTableModel modelAsistencia = (javax.swing.table.DefaultTableModel) tblAsistencia.getModel();
        javax.swing.table.DefaultTableModel modelNotas = (javax.swing.table.DefaultTableModel) tblNotas.getModel();
        javax.swing.table.DefaultTableModel modelMaterias1 = (javax.swing.table.DefaultTableModel) tblMaterias1.getModel();
        
        modelMaterias.setColumnIdentifiers(new String[]{"Nombre", "Código", "Cuatrimestre", "Año"});
        modelAsistencia.setColumnIdentifiers(new String[]{"Nombre", "Código", "Asistencia %"});
        modelNotas.setColumnIdentifiers(new String[]{"Nombre", "Código", "Promedio"});
        modelMaterias1.setColumnIdentifiers(new String[]{"Nombre", "Condición", "Asistencia %", "Promedio"});
        
        modelMaterias.setRowCount(0);
        modelAsistencia.setRowCount(0);
        modelNotas.setRowCount(0);
        modelMaterias1.setRowCount(0);
        
        javax.swing.DefaultListModel<String> alertasModel = new javax.swing.DefaultListModel<>();
        java.util.List<sistemaautogestion.zaratesilvachalimond.modelos.InscripcionMateria> materiasEnRiesgo = new java.util.ArrayList<>();
        
        int regulares = 0;
        int libres = 0;
        double sumaPromedios = 0;
        int matConNotas = 0;
        
        double maxNota = -1;
        double minNota = 11;
        double sumaAprobadas = 0;
        int cantAprobadas = 0;
        
        // Calcular estadísticas con TODAS las materias (inscripcionesDb)
        for (sistemaautogestion.zaratesilvachalimond.modelos.InscripcionMateria ins : inscripcionesDb) {
            double asistenciaPorc = ins.getPorcentajeAsistencia();
            
            if (ins.getCondicion().equals("Regular")) {
                regulares++;
            } else {
                libres++;
            }
            
            if (asistenciaPorc >= 75.0 && asistenciaPorc < 85.0) {
                materiasEnRiesgo.add(ins);
            }
            
            double promedioAux = ins.getPromedio();
            if (!ins.getNotas().isEmpty()) {
                sumaPromedios += promedioAux;
                matConNotas++;
            }

            // Reporte de materias APROBADAS: nota máxima, mínima y promedio sobre
            // TODAS las notas de las materias aprobadas (el conjunto completo, no una sola).
            if (ins.estaAprobada()) {
                for (Double nota : ins.getNotas()) {
                    if (nota > maxNota) maxNota = nota;
                    if (nota < minNota) minNota = nota;
                    sumaAprobadas += nota;
                    cantAprobadas++;
                }
            }
            
            String condicion = ins.getCondicion();
            modelMaterias1.addRow(new Object[]{ins.getMateria().getNombre(), condicion, String.format("%.2f%%", asistenciaPorc), String.format("%.2f", promedioAux)});
        }
        
        materiasEnRiesgo.sort((a, b) -> Double.compare(a.getPorcentajeAsistencia(), b.getPorcentajeAsistencia()));
        
        for (sistemaautogestion.zaratesilvachalimond.modelos.InscripcionMateria ins : materiasEnRiesgo) {
            double asistenciaPorc = ins.getPorcentajeAsistencia();
            alertasModel.addElement(ins.getMateria().getNombre() + " (" + String.format("%.2f%%", asistenciaPorc) + ")");
        }
        
        listaMaterias.setModel(alertasModel);
        lblRegulares.setText(String.valueOf(regulares));
        lblLibres.setText(String.valueOf(libres));
        lblRiesgo.setText(String.valueOf(alertasModel.size()));
        if (matConNotas > 0) {
            lblPromedio.setText(String.format("%.2f", sumaPromedios / matConNotas));
        } else {
            lblPromedio.setText("0.0");
        }
        
        if (cantAprobadas > 0) {
            lblMax.setText(String.format("%.2f", maxNota));
            lblMin.setText(String.format("%.2f", minNota));
            lblPromedioStats.setText(String.format("%.2f", sumaAprobadas / cantAprobadas));
        } else {
            lblMax.setText("0.0");
            lblMin.setText("0.0");
            lblPromedioStats.setText("0.0");
        }

        // Las 3 pestañas muestran TODAS las materias. La búsqueda resalta (no filtra).
        for (sistemaautogestion.zaratesilvachalimond.modelos.InscripcionMateria ins : inscripcionesDb) {
            modelMaterias.addRow(new Object[]{ins.getMateria().getNombre(), ins.getMateria().getCodigo(), ins.getMateria().getCuatrimestre(), ins.getMateria().getAnio()});
            modelAsistencia.addRow(new Object[]{ins.getMateria().getNombre(), ins.getMateria().getCodigo(), String.format("%.2f%%", ins.getPorcentajeAsistencia())});
            modelNotas.addRow(new Object[]{ins.getMateria().getNombre(), ins.getMateria().getCodigo(), String.format("%.2f", ins.getPromedio())});
        }

        // Estado vacío
        if (inscripcionesDb.isEmpty()) {
            modelMaterias.addRow(new Object[]{"No hay materias inscriptas", "", "", ""});
            modelAsistencia.addRow(new Object[]{"No hay materias inscriptas", "", ""});
            modelNotas.addRow(new Object[]{"No hay materias inscriptas", "", ""});
        }
    }

    // Busca en la tabla la primera materia que coincida (por nombre o código) y la resalta.
    // Muestra todas las filas; solo selecciona/marca la coincidencia (no filtra).
    private void buscarYResaltar(javax.swing.JTable tabla, String texto) {
        String f = texto.toLowerCase().trim();
        if (f.isEmpty()) {
            tabla.clearSelection();
            return;
        }
        for (int fila = 0; fila < tabla.getRowCount(); fila++) {
            String nombre = String.valueOf(tabla.getValueAt(fila, 0)).toLowerCase();
            String codigo = String.valueOf(tabla.getValueAt(fila, 1)).toLowerCase();
            if (nombre.contains(f) || codigo.contains(f)) {
                tabla.setRowSelectionInterval(fila, fila);
                tabla.scrollRectToVisible(tabla.getCellRect(fila, 0, true));
                return;
            }
        }
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ninguna materia que coincida con \"" + texto + "\".");
        tabla.clearSelection();
    }
    
    private void cargarDatosEnFormulario() {
        int fila = tblMaterias.getSelectedRow();
        if (fila == -1) return;

        // tblMaterias tiene las columnas: Nombre | Código | Cuatrimestre | Año.
        // Cargamos los 4 campos directamente desde la fila seleccionada.
        txtEditMateria.setText(String.valueOf(tblMaterias.getValueAt(fila, 0)));
        txtEditCodigo.setText(String.valueOf(tblMaterias.getValueAt(fila, 1)));
        txtEditCuatrimestre.setText(String.valueOf(tblMaterias.getValueAt(fila, 2)));
        txtEditAnio.setText(String.valueOf(tblMaterias.getValueAt(fila, 3)));

        // Guardamos el código original: es la clave para actualizar (por si el usuario lo cambia)
        codigoMateriaOriginal = String.valueOf(tblMaterias.getValueAt(fila, 1));
    }
    
    private void guardarCambiosMateria() {
        int fila = tblMaterias.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccioná una materia de la tabla para editar.");
            return;
        }

        String nuevoNombre = txtEditMateria.getText().trim();
        if (nuevoNombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.");
            return;
        }

        // El código que escribió el usuario (puede haberlo cambiado)
        String codigoNuevo = txtEditCodigo.getText().trim();

        // Cuatrimestre y año tienen que ser números, validamos antes de convertir
        int cuatrimestre;
        int anio;
        try {
            cuatrimestre = Integer.parseInt(txtEditCuatrimestre.getText().trim());
            anio = Integer.parseInt(txtEditAnio.getText().trim());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cuatrimestre y año deben ser números.");
            return;
        }

        // Se actualiza buscando por el código ORIGINAL (así el código también se puede cambiar)
        String msg = controlador.actualizarMateria(codigoMateriaOriginal, nuevoNombre, codigoNuevo, cuatrimestre, anio);
        javax.swing.JOptionPane.showMessageDialog(this, msg);

        // Refrescar las tablas para que se vea el cambio
        actualizarTablas();
    }

    private void registrarAsistencia() {
        if (controlador == null) return;
        int row = tblAsistencia.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione una materia de la tabla de Asistencia.");
            return;
        }
        if (legajoActual.isEmpty()) return;

        String nombreMateria = (String) tblAsistencia.getValueAt(row, 0);
        java.util.List<sistemaautogestion.zaratesilvachalimond.modelos.InscripcionMateria> inscripciones = controlador.listarInscripciones(legajoActual);
        String codigo = "";
        for (sistemaautogestion.zaratesilvachalimond.modelos.InscripcionMateria ins : inscripciones) {
            if (ins.getMateria().getNombre().equals(nombreMateria)) {
                codigo = ins.getMateria().getCodigo();
                break;
            }
        }
        
        if (!codigo.isEmpty()) {
            Object[] options = {"Presente", "Ausente"};
            int n = javax.swing.JOptionPane.showOptionDialog(this,
                "¿Desea registrar Presente o Ausente para " + nombreMateria + "?",
                "Registrar Asistencia",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
                
            if (n == javax.swing.JOptionPane.YES_OPTION || n == javax.swing.JOptionPane.NO_OPTION) {
                boolean presente = (n == javax.swing.JOptionPane.YES_OPTION);
                String msg = controlador.registrarAsistencia(legajoActual, codigo, presente);
                javax.swing.JOptionPane.showMessageDialog(this, msg);
                actualizarTablas();
            }
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AutogestionView(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnBuscar3;
    private javax.swing.JButton btnDarBajaMateria;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnNota;
    private javax.swing.JPanel cardperfil;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblAnioTag;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCarreraTag;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCuatrimestre;
    private javax.swing.JLabel lblIngresarPorMateria1;
    private javax.swing.JLabel lblIngresarPorMateria2;
    private javax.swing.JLabel lblIngresarPorMateria3;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblLibres;
    private javax.swing.JLabel lblLibresTag;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMaxTag;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblMinTag;
    private javax.swing.JLabel lblMisMaterias;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreTag;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblPromedioStats;
    private javax.swing.JLabel lblPromedioStatsTag;
    private javax.swing.JLabel lblPromedioTag;
    private javax.swing.JLabel lblRegulares;
    private javax.swing.JLabel lblRegularesTag;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblRiesgo;
    private javax.swing.JLabel lblRiesgoTag;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloDesaprobadas;
    private javax.swing.JLabel lblTituloEstadisticas;
    private javax.swing.JLabel lblTituloReportes;
    private javax.swing.JLabel lblTituloSeccionGeneral;
    private javax.swing.JLabel lblTituloSituacionGeneral;
    private javax.swing.JList<String> listaMaterias;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlEstadisticaAprobados;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlMisMaterias;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlSituacionGeneral;
    private javax.swing.JScrollPane scpMateriasDesaprobadas;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JSeparator sep4;
    private javax.swing.JPanel tabAsistencia;
    private javax.swing.JPanel tabMaterias;
    private javax.swing.JPanel tabNotas;
    private javax.swing.JTabbedPane tabbedMaterias;
    private javax.swing.JTable tblAsistencia;
    private javax.swing.JTable tblMaterias;
    private javax.swing.JTable tblMaterias1;
    private javax.swing.JTable tblNotas;
    private javax.swing.JTextField txtBuscar1;
    private javax.swing.JTextField txtBuscar2;
    private javax.swing.JTextField txtBuscar3;
    private javax.swing.JTextField txtEditAnio;
    private javax.swing.JTextField txtEditCodigo;
    private javax.swing.JTextField txtEditCuatrimestre;
    private javax.swing.JTextField txtEditMateria;
    // End of variables declaration//GEN-END:variables
}
