/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaautogestion.zaratesilvachalimond.vista;

import java.awt.CardLayout;

/**
 *
 * @author flore
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        CardLayout cl = (CardLayout) panelCentral.getLayout();
        cl.show(panelCentral, "inicio");

        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ((CardLayout) panelCentral.getLayout()).show(panelCentral, "panelInicio");
            }
        });
        lblMisMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ((CardLayout) panelCentral.getLayout()).show(panelCentral, "panelMisMaterias");
            }
        });
        lblReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ((CardLayout) panelCentral.getLayout()).show(panelCentral, "panelReportes");
            }
        });
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        lblMisMaterias = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        lblReportes = new javax.swing.JLabel();
        separador3 = new javax.swing.JSeparator();
        separador4 = new javax.swing.JSeparator();
        lblCerrar = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        cardperfil = new javax.swing.JPanel();
        lblNombreTag = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCarreraTag = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblAnioTag = new javax.swing.JLabel();
        lblTituloPerfil = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMaterias = new javax.swing.JList<>();
        lblTituloDesaprobadas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMaterias1 = new javax.swing.JList<>();
        lblTituloAprobadas = new javax.swing.JLabel();
        panelMisMaterias = new javax.swing.JPanel();
        panelReportes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de autogestión estudiantil");

        panelSidebar.setBackground(new java.awt.Color(22, 22, 26));
        panelSidebar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelSidebar.setForeground(new java.awt.Color(40, 40, 40));
        panelSidebar.setPreferredSize(new java.awt.Dimension(180, 600));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Autogestión alumnos");
        lblTitulo.setAlignmentX(0.5F);

        lblInicio.setBackground(new java.awt.Color(255, 255, 254));
        lblInicio.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblInicio.setText("Inicio");
        lblInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        separador1.setBackground(new java.awt.Color(127, 90, 240));
        separador1.setForeground(new java.awt.Color(40, 40, 40));
        separador1.setToolTipText("");

        lblMisMaterias.setBackground(new java.awt.Color(255, 255, 254));
        lblMisMaterias.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblMisMaterias.setText("Mis materias");
        lblMisMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        separador2.setBackground(new java.awt.Color(148, 161, 178));
        separador2.setForeground(new java.awt.Color(40, 40, 40));

        lblReportes.setBackground(new java.awt.Color(255, 255, 254));
        lblReportes.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblReportes.setText("Reportes");
        lblReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        separador3.setBackground(new java.awt.Color(148, 161, 178));
        separador3.setForeground(new java.awt.Color(40, 40, 40));

        separador4.setForeground(new java.awt.Color(40, 40, 40));

        lblCerrar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(114, 117, 126));
        lblCerrar.setText("Cerrar sesión");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador1)
            .addComponent(separador2)
            .addComponent(separador4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                        .addComponent(lblCerrar)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                        .addComponent(lblMisMaterias)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                        .addComponent(lblReportes)
                        .addGap(61, 61, 61))))
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblInicio))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTitulo)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(separador3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addGap(49, 49, 49)
                .addComponent(lblInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMisMaterias)
                .addGap(16, 16, 16)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReportes)
                .addGap(18, 18, 18)
                .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCerrar)
                .addGap(14, 14, 14))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        panelCentral.setBackground(new java.awt.Color(36, 38, 41));
        panelCentral.setToolTipText("");
        panelCentral.setLayout(new java.awt.CardLayout());

        panelInicio.setBackground(new java.awt.Color(22, 22, 26));
        panelInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 90, 240), 2, true));

        cardperfil.setBackground(new java.awt.Color(22, 22, 26));
        cardperfil.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cardperfil.setForeground(new java.awt.Color(127, 90, 240));

        lblNombreTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreTag.setForeground(new java.awt.Color(255, 255, 254));
        lblNombreTag.setText("Nombre:");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(148, 161, 178));
        lblNombre.setText("Ana García");

        lblCarreraTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCarreraTag.setForeground(new java.awt.Color(255, 255, 254));
        lblCarreraTag.setText("Carrera:");

        lblCarrera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCarrera.setForeground(new java.awt.Color(148, 161, 178));
        lblCarrera.setText("Analista en Sistemas");

        lblAnio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAnio.setForeground(new java.awt.Color(148, 161, 178));
        lblAnio.setText("2023");

        lblAnioTag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAnioTag.setForeground(new java.awt.Color(255, 255, 254));
        lblAnioTag.setText("Anio:");

        javax.swing.GroupLayout cardperfilLayout = new javax.swing.GroupLayout(cardperfil);
        cardperfil.setLayout(cardperfilLayout);
        cardperfilLayout.setHorizontalGroup(
            cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardperfilLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardperfilLayout.createSequentialGroup()
                        .addGroup(cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarreraTag)
                            .addComponent(lblNombreTag))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblCarrera)))
                    .addGroup(cardperfilLayout.createSequentialGroup()
                        .addComponent(lblAnioTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAnio)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        cardperfilLayout.setVerticalGroup(
            cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardperfilLayout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTag)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarreraTag)
                    .addComponent(lblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnioTag)
                    .addComponent(lblAnio))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblTituloPerfil.setBackground(new java.awt.Color(255, 255, 254));
        lblTituloPerfil.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTituloPerfil.setForeground(new java.awt.Color(255, 255, 254));
        lblTituloPerfil.setText("Mi perfil");

        listaMaterias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaMaterias);

        lblTituloDesaprobadas.setBackground(new java.awt.Color(255, 255, 254));
        lblTituloDesaprobadas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTituloDesaprobadas.setForeground(new java.awt.Color(255, 255, 254));
        lblTituloDesaprobadas.setText("Materias en riesgo");

        listaMaterias1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaMaterias1);

        lblTituloAprobadas.setBackground(new java.awt.Color(255, 255, 254));
        lblTituloAprobadas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTituloAprobadas.setForeground(new java.awt.Color(255, 255, 254));
        lblTituloAprobadas.setText("Materias aprobadas");

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTituloAprobadas)
                    .addComponent(lblTituloPerfil)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cardperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTituloDesaprobadas)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(45, 45, 45))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblTituloPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloDesaprobadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloAprobadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        panelCentral.add(panelInicio, "panelInicio");

        panelMisMaterias.setBackground(new java.awt.Color(22, 22, 26));

        javax.swing.GroupLayout panelMisMateriasLayout = new javax.swing.GroupLayout(panelMisMaterias);
        panelMisMaterias.setLayout(panelMisMateriasLayout);
        panelMisMateriasLayout.setHorizontalGroup(
            panelMisMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        panelMisMateriasLayout.setVerticalGroup(
            panelMisMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        panelCentral.add(panelMisMaterias, "panelMisMaterias");

        panelReportes.setBackground(new java.awt.Color(22, 22, 26));

        javax.swing.GroupLayout panelReportesLayout = new javax.swing.GroupLayout(panelReportes);
        panelReportes.setLayout(panelReportesLayout);
        panelReportesLayout.setHorizontalGroup(
            panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        panelReportesLayout.setVerticalGroup(
            panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        panelCentral.add(panelReportes, "panelReportes");

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardperfil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblAnioTag;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCarreraTag;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblMisMaterias;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreTag;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloAprobadas;
    private javax.swing.JLabel lblTituloDesaprobadas;
    private javax.swing.JLabel lblTituloPerfil;
    private javax.swing.JList<String> listaMaterias;
    private javax.swing.JList<String> listaMaterias1;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelMisMaterias;
    private javax.swing.JPanel panelReportes;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    // End of variables declaration//GEN-END:variables
}
